## 1. Numpy Theory

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### NumPy Made in C and Wrapped with Python

NumPy is mostly written in **C (and some C++)** and exposed to us through Python.

Python acts as a wrapper/interface layer, while the heavy computation runs in C.

---

#### 1. What Does "Written in C and Wrapped in Python" Mean?

When you write:

```python
import numpy as np
a = np.array([1, 2, 3])
```

You are calling Python functions.

But internally:

- Python calls C functions  
- The computation runs in C  
- The result is returned back to Python  

So NumPy feels like Python, but runs at C speed.

---

#### 2. Why Is NumPy Written in C?

NumPy is written in C because:

1. C is much faster than pure Python  
2. It allows direct memory management  
3. It stores data in contiguous memory  
4. Mathematical operations can be optimized at low level  

If NumPy were written purely in Python, it would be slow like normal Python loops.

---

#### 3. How Is C Connected to Python?

Python connects to C using:

- CPython C API  
- C extension modules  
- Cython (in some parts)  

Example:

```python
a.sum()
```

Internally:

- Python calls a C function  
- The loop runs in C  
- The result is returned to Python  

This is why NumPy is much faster than Python loops.

---

#### 4. Speed Comparison Example

Pure Python:

```python
sum([1, 2, 3, 4, 5])
```

NumPy:

```python
np.sum(np.array([1, 2, 3, 4, 5]))
```

For large arrays, NumPy is much faster because the loop runs in C instead of Python.

---

#### 5. Important Insight

Most major ML libraries follow this structure:

- NumPy --> C backend  
- TensorFlow --> C++ backend  
- PyTorch --> C++ backend  
- OpenCV --> C++ backend  

Python is used for:

- Clean and readable code  
- Easy API  
- Fast development  

C/C++ is used for:

- Speed  
- Heavy computation  
- Efficient memory handling  

---

#### 6. Memory Difference: NumPy Array vs Python List

##### NumPy Array

- Stored in contiguous memory  
- Fixed data type  
- No object overhead per element  
- Very memory efficient  

##### Python List

- Stores references to objects  
- Each element is a Python object  
- More memory usage  
- Slower for numerical computation  

---

#### Final Summary

NumPy is mainly written in C and wrapped with Python so that:

- It feels like Python  
- But runs at C speed  

## 2. Creating Numpy Arrays

In [1]:
# np.array
import numpy as np             # we are giving np as shorthand of numpy

a = np.array([1,2,3])
print(a)
print(type(a))

# this is 1D numpy array and can also be called vector

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# 2D

b = np.array([[1,2,3],[4,5,6]])
print(b)

# this is 2D numpy array and can also be called matrix

[[1 2 3]
 [4 5 6]]


In [11]:
# 3D

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

# this is 3D numpy array and can also be called tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
# dtype

f = np.array([1,2,3], dtype=float)

b = np.array([0,1,2,3], dtype=bool)

print(f)
print(type(f))

print()

print(b)
print(type(b))


[1. 2. 3.]
<class 'numpy.ndarray'>

[False  True  True  True]
<class 'numpy.ndarray'>


In [17]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# with reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.arange(1,11).reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [40]:
np.arange(16).reshape(2,2,2,2)
# this is a 4D array

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [25]:
# np.arange(1,11).reshape(6,2)

# --> ValueError: cannot reshape array of size 10 into shape (6,2)

# There are 10 elements in the array and we are reshaping it into (6,2), which becomes 12 elements, so it is not possible

In [26]:
# np.ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
# np.random

np.random.random((3,4))

array([[0.49079849, 0.04863487, 0.48898414, 0.59879717],
       [0.8522045 , 0.59467454, 0.93931842, 0.06911617],
       [0.6187952 , 0.89797413, 0.74130672, 0.77332415]])

In [33]:
# np.ones, np.zeros and np.random.random are functions used to initialize arrays

In [35]:
# np.linspace

np.linspace(-10, 10, 10)

# First argument is the start value
# Second argument is the end value
# Third argument is the number of evenly spaced elements to generate

# # linspace generates linearly spaced points within a given range

# Linearly spaced means:  The difference between consecutive values is constant.
# The gap between each number will be equal.

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [38]:
np.linspace(-10, 10, 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [37]:
# np.identity

np.identity(3)


# An identity matrix is a square matrix where:
# All diagonal elements are 1
# All other elements are 0

# Important Points:  
# The argument must be a single number.
    
# That number represents both rows and columns.

# Identity matrix is always square.

# Data type is float by default.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 3. Array Attributes

In [82]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1,'\n')
print(a2,'\n')
print(a3,'\n')

[0 1 2 3 4 5 6 7 8 9] 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



In [48]:
# ndim (no. of dimensions)

print(a1.ndim)    #1D
print(a2.ndim)    #2D
print(a3.ndim)    #3D

# .ndim returns the number of axes or dimensions of a NumPy array.
# Important: Dimension means how many directions you need to move to access elements.

1
2
3


In [50]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)

# .shape returns a tuple that tells the size of the array in each dimension.
# It tells how many elements exist along each axis.

(10,)
(3, 4)
(2, 2, 2)


In [53]:
# size

print(a1.size)
print(a2.size)
print(a3.size)

# .size returns the total number of elements in the array.
# It counts all elements across all dimensions.

10
12
8


In [57]:
# itemsize

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)


# .itemsize returns the size in bytes of each element in the array.
# Important: It tells memory used by one element, not the whole array.

8
8
8


In [61]:
a = np.array([1, 2, 3], dtype=np.int32)
print(a.itemsize)

# int64  -> 8 bytes
# int32  -> 4 bytes
# float64 -> 8 bytes
# float32 -> 4 bytes

4


In [62]:
# dtype

print(a.dtype)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

# .dtype tells the data type of elements stored in the NumPy array.
# It tells what type of data each element is stored as internally.

int32
int64
float64
int64


In [65]:
a = np.array([1, 2.5, 3])
print(a.dtype)

# Why float
# Because NumPy promotes smaller type to larger compatible type.
# This is called type promotion.
# 8 bits = 1 byte

float64


## 4. Changing Datatype

In [83]:
# astype

print(a3.dtype,'\n')

# The data type of a3 is int64.
# If we do not need large range integers,
# we can convert it to a smaller data type to save memory.

a3 = a3.astype(np.int32)
print(a3)
print(a3.dtype)

# .astype() creates a new array with a different data type.
# Important: It does not modify the original array unless you reassign it.

int64 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int32


## 5. Array Operations

In [89]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)


print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [95]:
# scalar Operation

# Arithmetic

print(a1 * 2, '\n')      # a1 is a matrix and 2 is a scalar, Scalar means a single number

print(a1 + 2, '\n')

print(a1 - 2, '\n')

print(a1 / 2, '\n')

print(a1 ** 2, '\n')

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]] 

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]] 

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]] 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 



In [105]:
# Relational

print(a2 > 5, '\n')

print(a2 > 20, '\n')

print(a2 == 15, '\n')

# These are element wise comparison operations
# Relational operations return boolean arrays

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False False]
 [False False False False]
 [False  True  True  True]] 

[[False False False  True]
 [False False False False]
 [False False False False]] 



In [107]:
# Vector Operation

# Arithmetic

print(a1 + a2, '\n')

print(a1 - a2, '\n')

print(a1 * a2, '\n')

print(a1 / a2, '\n')

print(a1 ** a2, '\n')

# These are element wise operations between two arrays

# Important condition:
# Both arrays must have the same shape.
# If shapes are different and not compatible, NumPy will raise an error.

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]] 

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]] 

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]] 



In [110]:
# Relational Operations (Array vs Array)

print(a1 > a2, '\n')

print(a1 < a2, '\n')

print(a1 == a2, '\n')

[[False False False False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False False]
 [False False False False]
 [False False False False]] 



## 6. Array Functions

In [11]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[73. 93. 66.]
 [84. 12. 12.]
 [41. 94. 67.]]


In [12]:
# max/min/sum/prod


print("max:",np.max(a1))

print("min:",np.min(a1))

print("sum:",np.sum(a1))

print("prod:",np.prod(a1))

max: 94.0
min: 12.0
sum: 542.0
prod: 1399516539708672.0


In [13]:
# axis concept
# axis = 0 means column wise
# axis = 1 means row wise
# 0--> column and 1--> row

print("max of col:",np.max(a1, axis=0))
print("max of row:",np.max(a1, axis=1),'\n')


print("min of col:",np.min(a1, axis=0))
print("min of row:",np.min(a1, axis=1),'\n')


print("sum of col:",np.sum(a1, axis=0))
print("sum of row:",np.sum(a1, axis=1),'\n')


print("prod of col:",np.prod(a1, axis=0))
print("prod of row:",np.prod(a1, axis=1),'\n')


max of col: [84. 94. 67.]
max of row: [93. 84. 94.] 

min of col: [41. 12. 12.]
min of row: [66. 12. 41.] 

sum of col: [198. 199. 145.]
sum of row: [232. 108. 202.] 

prod of col: [251412. 104904.  53064.]
prod of row: [448074.  12096. 258218.] 



Axis number tells which dimension is being reduced.

In 2D:

Axis 0 collapses rows and keeps columns.

Axis 1 collapses columns and keeps rows.

That is the correct conceptual way to think.

0 means column wise and 1 means row wise

In [16]:
# mean/median/std/var

print("mean:",np.mean(a1))

print("median:",np.median(a1))

print("std:",np.std(a1))

print("var:",np.var(a1))

mean: 60.22222222222222
median: 67.0
std: 29.895290516429647
var: 893.7283950617283


In [17]:
print("mean of col:",np.mean(a1, axis=0))
print("mean of row:",np.mean(a1, axis=1),'\n')


print("median of col:",np.median(a1, axis=0))
print("median of row:",np.median(a1, axis=1),'\n')


print("std of col:",np.std(a1, axis=0))
print("std of row:",np.std(a1, axis=1),'\n')


print("var of col:",np.var(a1, axis=0))
print("var of row:",np.var(a1, axis=1),'\n')

mean of col: [66.         66.33333333 48.33333333]
mean of row: [77.33333333 36.         67.33333333] 

median of col: [73. 93. 66.]
median of row: [73. 12. 67.] 

std of col: [18.23915203 38.42163742 25.69478979]
std of row: [11.4406682  33.9411255  21.63844316] 

var of col: [ 332.66666667 1476.22222222  660.22222222]
var of row: [ 130.88888889 1152.          468.22222222] 



```
1. Mean
The average of all values.
Calculated as sum of values divided by total number of values.

2. Median
The middle value after sorting the data.
If there are two middle values, it is their average.

3. Standard Deviation
Measures how much the values spread out from the mean.
Higher value means more spread.

4. Variance
Measures how far values are from the mean on average.
It is the square of the standard deviation.

```

In [18]:
# trigonometric function

print(np.sin(a1))

[[-0.67677196 -0.94828214 -0.02655115]
 [ 0.73319032 -0.53657292 -0.53657292]
 [-0.15862267 -0.24525199 -0.85551998]]


In [145]:
# Dot Product (Matrix Multiplication)

a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

print(a2, '\n')
print(a3, '\n')

np.dot(a2, a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 



array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [146]:
a2 @ a3    # simpler syntax

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#### Dot Product (Matrix Multiplication)

The dot product is a method of multiplying two matrices following specific rules.

---

#### Rules of Dot Product

##### 1. Inner Dimensions Must Match

If matrix A has shape (m, n)  
And matrix B has shape (n, p)  

Then multiplication is possible.

If the inner dimensions do not match, multiplication is not allowed.

---

##### 2. Shape of Result

If A is (m, n)  
And B is (n, p)  

Then result will have shape (m, p)

Rows come from the first matrix.  
Columns come from the second matrix.

---

##### 3. Order Matters

Matrix multiplication is not commutative.

A × B is not equal to B × A

---

##### 4. It Is Not Element Wise Multiplication

Dot product multiplies rows with columns and then adds the results.

It is different from element wise multiplication using the asterisk operator.

---

#### How Dot Product Is Performed

Suppose:

Matrix A:

```
[[1 2]
 [3 4]]
```

Matrix B:

```
[[5 6]
 [7 8]]
```

To calculate the first element of the result:

Take first row of A and first column of B.

Multiply corresponding elements and add them:

(1 × 5) + (2 × 7)

To calculate the next element:

Take first row of A and second column of B:

(1 × 6) + (2 × 8)

---

#### Memory Trick

Row of first matrix  
Column of second matrix  

Multiply and add.

---

#### Why It Is Important

Dot product is used in:

- Neural networks  
- Linear regression  
- Logistic regression  
- Machine learning models  

Most ML computations rely on matrix multiplication.

In [148]:
# log and exponets

print(np.log(a1))
print()
print(np.exp(a1))

[[3.13549422 3.87120101 3.61091791]
 [3.33220451 4.07753744 4.47733681]
 [4.06044301 4.00733319 4.17438727]]

[[9.74480345e+09 7.01673591e+20 1.17191424e+16]
 [1.44625706e+12 4.20121040e+25 1.65163625e+38]
 [1.54553894e+25 7.69478527e+23 1.69488924e+28]]


In [166]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[28., 95., 64.],
       [10., 61., 33.]])

In [163]:
np.floor(np.random.random((2,3))*100)

array([[13., 13., 60.],
       [71., 27., 15.]])

In [164]:
np.ceil(np.random.random((2,3))*100)

array([[54., 56.,  1.],
       [71., 55., 68.]])

```python
1. np.round()
Rounds values to the nearest integer.
Example:
45.3 becomes 45
45.7 becomes 46


2. np.floor()
Always rounds down to the lower integer.
Example:
45.9 becomes 45
45.1 becomes 45


3. np.ceil()
Always rounds up to the higher integer.
Example:
45.1 becomes 46
45.9 becomes 46

```

## 7. Indexing and Slicing

In [167]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1,'\n')
print(a2,'\n')
print(a3,'\n')

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



In [170]:
print(a1[-1])
print(a1[0])

9
0


In [177]:
print(a2[1,2])
print(a2[2,3])

6
11


In [183]:
print(a3[1,0,1])
print(a3[0,1,0])
print(a3[0,0,0])
print(a3[1,1,0])

5
2
0
6


In [184]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
a1[2:5]

array([2, 3, 4])

In [186]:
a1[2:5:2]

array([2, 4])

In [187]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
a2[0,:]

array([0, 1, 2, 3])

In [192]:
a2[:,2]

array([ 2,  6, 10])

In [193]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [197]:
a2[0:3:2, 0:5:3]

array([[ 0,  3],
       [ 8, 11]])

In [199]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [201]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [202]:
a2[1,::3]

array([4, 7])

In [203]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [205]:
a2[:2, 1::2]

array([[1, 3],
       [5, 7]])

In [208]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [209]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [211]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [212]:
a3[0, 1]

array([3, 4, 5])

In [221]:
a3[1, :,1]

array([10, 13, 16])

In [222]:
a3[2, 1:,1:]

array([[22, 23],
       [25, 26]])

In [226]:
a3[::2, 0,::2]

array([[ 0,  2],
       [18, 20]])

## 8. Iterating

In [231]:
print(a1,'\n')
print(a2,'\n')
print(a3,'\n')

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 



In [234]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [236]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [239]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [243]:
for i in np.nditer(a3):
    print(i)

# np.nditer() is an efficient iterator for NumPy arrays.
# It allows you to iterate over all elements of the array one by one.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## 9. Reshaping

In [244]:
# reshape

In [246]:
# Transpose
a2

# Transpose means converting rows into columns and columns into rows.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [248]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [250]:
a2.T     #simple syntax

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [255]:
# ravel
a2

# Ravel converts a multi dimensional array into a 1D array.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [256]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [257]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [258]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## 10. Stacking

In [4]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4, '\n')
print(a5, '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 



In [5]:
# Horizontal Stacking

np.hstack((a4,a5))

# Important rule:
# Number of rows must be the same.

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [267]:
# Vertical Stacking

np.vstack((a4,a5))

# Important rule:
# Number of columns must be the same.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

```
hstack:
Adds horizontally
Columns increase

vstack:
Adds vertically
Rows increase
```

## 11. Splitting

In [268]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [270]:
# Horizontal Splitting

np.hsplit(a4, 2)



# np.hsplit(a4, n)
# Splits the array column wise into n equal parts.
    
# Important rule:
# Number of columns must be divisible by n.

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [274]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [275]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [276]:
# Vertical splitting

np.vsplit(a5,3)


# np.vsplit(a5, n)
# Splits the array row wise into n equal parts.

# Important rule:
# Number of rows must be divisible by n.

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [277]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

```
hsplit:
Cuts vertically
Columns are divided

vsplit:
Cuts horizontally
Rows are divided
```