**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
a = np.nan*np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [29]:
a = int(input("Enter the first shape value: "))
b = int(input("Enter the second shape value: "))

arr = np.random.random((a, b))

print("Generated Array:\n", arr)
print("\nAverage:", np.mean(arr))

print("Average:", arr.mean())

Enter the first shape value:  3
Enter the second shape value:  4


Generated Array:
 [[0.59253124 0.62898181 0.57769834 0.31671718]
 [0.13240936 0.55097471 0.04219328 0.84260965]
 [0.00262001 0.39599125 0.23817198 0.34970314]]

Average: 0.3892168296822694
Average: 0.3892168296822694


In [7]:
a,b = map(int, input("Enter the number ").split())

x = np.random.random((a,b))
print(x)
print()
print(x.mean())

Enter the number  3 4


[[0.32279022 0.48915665 0.77155702 0.98706227]
 [0.44962701 0.41103066 0.83758225 0.97773921]
 [0.41557867 0.9122256  0.78140872 0.68229091]]

0.6698374317140505


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [8]:
def createArr(a,b):
    
    arr = np.zeros((a,b))
    arr[0]=1
    arr[-1]=1
    arr[:,0]=1
    arr[:,-1]=1

    return arr

print(createArr(4,4),'\n')
print(createArr(10,10),'\n')

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 



### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [9]:
arr = np.linspace(0,1,10)
print(arr)

print(arr[1:-1])

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


In [67]:
# better code

np.linspace(0,1,12)[1:-1]

# there are 10 values between 1 to 0 and 1 and 0 are excluded

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [13]:
print(np.identity(3))
print()
print(np.eye(3))

# An identity matrix is a square matrix where:
    # Number of rows = number of columns
    # Diagonal elements are 1
    # All other elements are 0

# So:
# Shape (3,4) means:
# 3 rows
# 4 columns

# That is not square.

# A true identity matrix of shape (3,4) is NOT possible.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [81]:
arr = np.arange(5)

np.vstack((arr,arr,arr,arr,arr))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [4]:
# better code

np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# np.tile() repeats an array multiple times in a grid-like pattern.

# Simple syntax:
# np.tile(array, (rows_repeat, columns_repeat))

In [16]:
x = np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


*Distance = √[(x1 − x2)² + (y1 − y2)²]*

In [19]:
sample = np.random.randint(1,100,20).reshape(10,2)
point = np.array([2,3])

distance=[]
for i in sample:
    x = i[0] 
    y = i[1] 

    d = ((x-point[0])**2 + (y-point[1])**2)**0.5

    distance.append(int(d))

distance = np.array(distance)

print("Sample:\n",sample)
print("\nDistance:\n",distance)

Sample:
 [[49 51]
 [99 55]
 [32 30]
 [93 13]
 [33 39]
 [ 2 67]
 [22 50]
 [38 38]
 [35 80]
 [99 42]]

Distance:
 [ 67 110  40  91  47  64  51  50  83 104]


In [6]:
sample = np.random.randint(1,100,(10,2))
point = np.array([2,3])

dist = np.sqrt(np.sum((sample - point)**2, axis=1)).astype(int)

print("Sample:\n", sample)
print("\nDistance:\n", dist)

Sample:
 [[80 70]
 [12 18]
 [26 52]
 [33 32]
 [54 59]
 [46 21]
 [74 93]
 [82 57]
 [ 5 85]
 [40 81]]

Distance:
 [102  18  54  42  76  47 115  96  82  86]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
index = 99   # because 100th element
np.unravel_index(index, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

In [17]:
x, y, z = np.unravel_index(99, (6,7,8))
print(int(x), int(y), int(z))

1 5 3


```python
np.unravel_index(indices, shape, order='C')
```
```
indices
The flat index (or list of flat indices).

shape
The shape of the array.

order (optional)
'C' → row-major order (default)
'F' → column-major order (Fortran style)
```

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [22]:
L = [1, 2, 3, 4, -8, -10]

L = np.array(L).astype(np.float32)

print(L[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [23]:
# Take input
arr = input().strip().split()

# Convert to NumPy float array
arr = np.array(arr, dtype=float)

# Reverse and print
print(arr[::-1])

 1 2 3 4 -8 -10


[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [43]:
arr = np.array([1, 2])

count=0
for i in np.nditer(arr):
    count+=1

print(f"elements_count: {count}")

elements_count: 2


In [45]:
# Optimal Code

arr = np.array([1, 2])
print("elements_count :", arr.size)

elements_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [7]:
import numpy as np

def softmax(array):

    if not isinstance(array, np.ndarray):
        raise TypeError("Input must be numpy ndarray")
    
    if array.ndim != 1:
        raise ValueError("Input must be 1D array")
    
    # Numerical stability trick
    array = array - np.max(array)
    
    exp_values = np.exp(array)
    sum_exp = np.sum(exp_values)
    
    return exp_values / sum_exp

arr = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])

softmax(arr)

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [30]:
def stack(*args):

    for i in args:
        if type(i)!= np.ndarray:
            raise TypeError("Requires Numpy Array")
    
    return np.vstack(args)


a= np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
     [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

print(stack(a,b,c))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [55]:
import random
def date_array(start, end):

    dates = start.split("-")
    end_dates = end.split("-")
    L=[]        
    minus = int(end_dates[2]) - int(dates[2])

    nums = np.linspace(int(dates[2]), int(end_dates[2]), minus, dtype=int)
    
    for i in nums:
        L.append(f"{dates[0]}-{dates[1]}-{i}")

    return L

date_array(start = '2020-09-15', end = '2020-09-25')



['2020-09-15',
 '2020-09-16',
 '2020-09-17',
 '2020-09-18',
 '2020-09-19',
 '2020-09-20',
 '2020-09-21',
 '2020-09-22',
 '2020-09-23',
 '2020-09-25']

In [38]:
# better code

from datetime import datetime, timedelta

def date_array(start, end):

    if type(start) != str or type(end)!=str:
        raise TypeError
    
    start_date = datetime.strptime(start, "%Y-%m-%d")
    end_date = datetime.strptime(end, "%Y-%m-%d")
    
    result = []
    
    while start_date <= end_date:
        result.append(start_date.strftime("%Y-%m-%d"))
        start_date += timedelta(days=1)
    
    return result

date_array(start = '2020-09-15', end = '2020-09-25')

['2020-09-15',
 '2020-09-16',
 '2020-09-17',
 '2020-09-18',
 '2020-09-19',
 '2020-09-20',
 '2020-09-21',
 '2020-09-22',
 '2020-09-23',
 '2020-09-24',
 '2020-09-25']

### `Q-14:` Subtract the mean of each row from a matrix.

In [7]:
arr = np.random.random((3,3))
arr = np.round(arr*100)

print(arr)

[[32. 14. 51.]
 [49. 34. 35.]
 [31. 94. 91.]]


In [10]:
mean_arr = np.mean(arr, axis=1, keepdims=True)
print(mean_arr)
print()
result = arr - mean_arr
print(result)

[[32.33333333]
 [39.33333333]
 [72.        ]]

[[ -0.33333333 -18.33333333  18.66666667]
 [  9.66666667  -5.33333333  -4.33333333]
 [-41.          22.          19.        ]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [11]:
a = np.arange(9).reshape(3,3)
print(a)
a[:,[0,2,1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [48]:
a = np.arange(10)
print(a)
print(a%2==1)
a[a%2 == 1] = -1
a

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [52]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

print(b>a)
a[b>a] = b[a<b]
a

[False False False  True False]


array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [56]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7496, 2301, 1042, 1811, 1091],
       [5760, 9552, 9094, 9616, 9519],
       [8442, 2662, 9992, 1020, 1614],
       [2494, 6970, 1325, 5059, 3290],
       [3910, 3621, 3970, 1815,  142],
       [6742, 8202, 7946, 1961, 9924],
       [2878,  344, 9555, 7362,  182],
       [ 850, 7968, 2160, 4803, 5172]], dtype=int32)

In [59]:
arr1[:,::2]

array([[7496, 1042, 1091],
       [5760, 9094, 9519],
       [8442, 9992, 1614],
       [2494, 1325, 3290],
       [3910, 3970,  142],
       [6742, 7946, 9924],
       [2878, 9555,  182],
       [ 850, 2160, 5172]], dtype=int32)

In [61]:
(arr1-arr1.min()) / (arr1.max() - arr1.min())

array([[0.74659898, 0.21918782, 0.09137056, 0.16944162, 0.09634518],
       [0.57035533, 0.95532995, 0.90883249, 0.96182741, 0.9519797 ],
       [0.84263959, 0.25583756, 1.        , 0.08913706, 0.14944162],
       [0.23878173, 0.69319797, 0.12010152, 0.49918782, 0.31959391],
       [0.38253807, 0.35319797, 0.38862944, 0.16984772, 0.        ],
       [0.67005076, 0.81827411, 0.79228426, 0.18467005, 0.99309645],
       [0.2777665 , 0.02050761, 0.95563452, 0.73299492, 0.00406091],
       [0.07187817, 0.79451777, 0.2048731 , 0.47319797, 0.5106599 ]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [66]:
def nthmax(arr,n):

    if n>len(arr):
        raise IndexError("n is way out of limit")

    arr.sort()
    return arr[-n]

print(nthmax(np.array([12,34,40,7,1,0]) ,3))
print(nthmax(np.array([12,34,40,7,1,0]) ,1))

12
40


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [14]:
a = np.array([1,2,3])

print(np.repeat(a,3))
print(np.tile(a,3))


np.hstack([np.repeat(a,3), np.tile(a,3)])

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])