In [1]:
import numpy as np

## 1. np.sort 

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
a = np.random.randint(1,100,15)
a

array([95, 22,  9,  1, 80, 46, 48, 74, 78, 28, 48, 17, 17, 15, 70],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[28, 90,  3,  7],
       [34, 39, 53, 20],
       [11,  6, 64, 58],
       [50, 52,  2, 26],
       [69, 77, 59, 75],
       [20, 75,  3, 52]], dtype=int32)

In [6]:
np.sort(a)

array([ 1,  9, 15, 17, 17, 22, 28, 46, 48, 48, 70, 74, 78, 80, 95],
      dtype=int32)

In [7]:
np.sort(a)[::-1]   # reverse sorting

array([95, 80, 78, 74, 70, 48, 48, 46, 28, 22, 17, 17, 15,  9,  1],
      dtype=int32)

In [8]:
# row-wise sort
np.sort(b)

array([[ 3,  7, 28, 90],
       [20, 34, 39, 53],
       [ 6, 11, 58, 64],
       [ 2, 26, 50, 52],
       [59, 69, 75, 77],
       [ 3, 20, 52, 75]], dtype=int32)

In [9]:
# column-wise sort
np.sort(b, axis=0)

array([[11,  6,  2,  7],
       [20, 39,  3, 20],
       [28, 52,  3, 26],
       [34, 75, 53, 52],
       [50, 77, 59, 58],
       [69, 90, 64, 75]], dtype=int32)

In [10]:
np.sort(b, axis=0)[::-1]

array([[69, 90, 64, 75],
       [50, 77, 59, 58],
       [34, 75, 53, 52],
       [28, 52,  3, 26],
       [20, 39,  3, 20],
       [11,  6,  2,  7]], dtype=int32)

## 2. np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
a

array([95, 22,  9,  1, 80, 46, 48, 74, 78, 28, 48, 17, 17, 15, 70],
      dtype=int32)

In [12]:
np.append(a,200)

array([ 95,  22,   9,   1,  80,  46,  48,  74,  78,  28,  48,  17,  17,
        15,  70, 200])

In [13]:
b

array([[28, 90,  3,  7],
       [34, 39, 53, 20],
       [11,  6, 64, 58],
       [50, 52,  2, 26],
       [69, 77, 59, 75],
       [20, 75,  3, 52]], dtype=int32)

In [15]:
np.append(b,np.ones((b.shape[0],1)), axis=1)

array([[28., 90.,  3.,  7.,  1.],
       [34., 39., 53., 20.,  1.],
       [11.,  6., 64., 58.,  1.],
       [50., 52.,  2., 26.,  1.],
       [69., 77., 59., 75.,  1.],
       [20., 75.,  3., 52.,  1.]])

In [27]:
np.ones((6,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [16]:
np.append(b,np.random.random((b.shape[0],1)), axis=1)

array([[28.        , 90.        ,  3.        ,  7.        ,  0.83235951],
       [34.        , 39.        , 53.        , 20.        ,  0.78468166],
       [11.        ,  6.        , 64.        , 58.        ,  0.10846086],
       [50.        , 52.        ,  2.        , 26.        ,  0.67814992],
       [69.        , 77.        , 59.        , 75.        ,  0.45371183],
       [20.        , 75.        ,  3.        , 52.        ,  0.34187262]])

In [17]:
b.shape

(6, 4)

In [18]:
b.shape[0]

6

## 3. np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [24]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [27]:
np.concatenate((c,d), axis=0)   # row

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.concatenate((c,d), axis=1)   # columns

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## 4. np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [31]:
e = np.array([1,1,1,2,2,3,3,3,4,5,5,5,6])

In [32]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## 5. np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [36]:
print(a)
print(a.shape)

[99 32 75 68 76 31 49 78 18 97  6 59 32 68 35]
(15,)


In [38]:
np.expand_dims(a, axis=0)

array([[99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35]],
      dtype=int32)

In [39]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [40]:
np.expand_dims(a, axis=1)

array([[99],
       [32],
       [75],
       [68],
       [76],
       [31],
       [49],
       [78],
       [18],
       [97],
       [ 6],
       [59],
       [32],
       [68],
       [35]], dtype=int32)

In [42]:
np.expand_dims(a, axis=1).shape

(15, 1)

## 6. np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [44]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [46]:
# find all indices with value greater than 50

np.where(a>50)

array([99, 75, 68, 76, 78, 97, 59, 68], dtype=int32)

In [47]:
a[np.where(a>50)]

array([99, 75, 68, 76, 78, 97, 59, 68], dtype=int32)

In [48]:
# replace all values > 50 with 0

# syntax: np.where(condition, true, false)

np.where(a>50, 0, a)

array([ 0, 32,  0,  0,  0, 31, 49,  0, 18,  0,  6,  0, 32,  0, 35],
      dtype=int32)

In [49]:
np.where(a%2==0, 0, a)

array([99,  0, 75,  0,  0, 31, 49,  0,  0, 97,  0, 59,  0,  0, 35],
      dtype=int32)

## 7. np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [50]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [51]:
np.argmax(a)

np.int64(0)

In [53]:
a[np.argmax(a)]

np.int32(99)

In [55]:
b

array([[12, 35, 33, 15],
       [48, 53, 35, 66],
       [99, 72, 63, 95],
       [85, 92, 43, 10],
       [18, 86,  3, 74],
       [69, 71, 66, 10]], dtype=int32)

In [59]:
np.argmax(b, axis=0)   # column

array([2, 3, 5, 2])

In [60]:
np.argmax(b, axis=1)   # row

array([1, 3, 0, 1, 1, 1])

In [61]:
np.argmax(b)

np.int64(8)

## 8. np.argmin

The numpy.argmin() function returns indices of the min element of the array in a particular axis.

In [64]:
np.argmin(a)

np.int64(10)

In [65]:
a[np.argmin(a)]

np.int32(6)

In [66]:
np.argmin(b, axis=0)   # column

array([0, 0, 4, 3])

In [67]:
np.argmin(b, axis=1)   # row

array([0, 2, 2, 3, 2, 3])

## 9. np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [70]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [71]:
np.cumsum(a)

array([ 99, 131, 206, 274, 350, 381, 430, 508, 526, 623, 629, 688, 720,
       788, 823])

In [72]:
b

array([[12, 35, 33, 15],
       [48, 53, 35, 66],
       [99, 72, 63, 95],
       [85, 92, 43, 10],
       [18, 86,  3, 74],
       [69, 71, 66, 10]], dtype=int32)

In [74]:
np.cumsum(b)        # converted this into 1D

array([  12,   47,   80,   95,  143,  196,  231,  297,  396,  468,  531,
        626,  711,  803,  846,  856,  874,  960,  963, 1037, 1106, 1177,
       1243, 1253])

In [75]:
np.cumsum(b, axis=0)   # column

array([[ 12,  35,  33,  15],
       [ 60,  88,  68,  81],
       [159, 160, 131, 176],
       [244, 252, 174, 186],
       [262, 338, 177, 260],
       [331, 409, 243, 270]])

In [76]:
np.cumsum(b, axis=1)   # row

array([[ 12,  47,  80,  95],
       [ 48, 101, 136, 202],
       [ 99, 171, 234, 329],
       [ 85, 177, 220, 230],
       [ 18, 104, 107, 181],
       [ 69, 140, 206, 216]])

## 10. np.cumprod

numpy.cumsum() function is used when we want to compute the cumulative product of array elements over a given axis.

In [79]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [81]:
np.cumprod(a)

array([                  99,                 3168,               237600,
                   16156800,           1227916800,          38065420800,
              1865205619200,      145486038297600,     2618748689356800,
         254018622867609600,  1524111737205657600, -2311127873413959680,
        -169115654408503296,  6946879573931327488,  3333112129372291072])

## 11. np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [82]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [83]:
np.percentile(a,100)          # it gives the number with hightest percentile

np.float64(99.0)

In [84]:
np.percentile(a,0)

np.float64(6.0)

In [85]:
np.percentile(a,50)

np.float64(59.0)

In [86]:
np.median(a)

np.float64(59.0)

<img src="https://media.geeksforgeeks.org/wp-content/uploads/20250724172357265328/frame_16.webp" width=500>

## 12. np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [88]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [89]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 0, 4, 1, 1, 2, 3, 0, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [91]:
np.histogram(a, bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

## 13. np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [92]:
salary = np.array([2000, 4000, 25000, 35000, 60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.19773323],
       [0.19773323, 1.        ]])


|            | Salary | Experience |
|------------|--------|------------|
| **Salary** | 1.00   |  0.19     |
| **Experience** |  0.19   | 1.00    |



As experience increases, salary tends to increase, but the relationship is not very strong

## 14. np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [94]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [96]:
items = [10,15,30,35,50,70,75,100]

np.isin(a,items)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [97]:
a[np.isin(a,items)]

array([75, 35], dtype=int32)

## 15. np.filp

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [100]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [101]:
np.flip(a)

array([35, 68, 32, 59,  6, 97, 18, 78, 49, 31, 76, 68, 75, 32, 99],
      dtype=int32)

In [103]:
b

array([[12, 35, 33, 15],
       [48, 53, 35, 66],
       [99, 72, 63, 95],
       [85, 92, 43, 10],
       [18, 86,  3, 74],
       [69, 71, 66, 10]], dtype=int32)

In [104]:
np.flip(b)

array([[10, 66, 71, 69],
       [74,  3, 86, 18],
       [10, 43, 92, 85],
       [95, 63, 72, 99],
       [66, 35, 53, 48],
       [15, 33, 35, 12]], dtype=int32)

In [105]:
np.flip(b,axis=0)

array([[69, 71, 66, 10],
       [18, 86,  3, 74],
       [85, 92, 43, 10],
       [99, 72, 63, 95],
       [48, 53, 35, 66],
       [12, 35, 33, 15]], dtype=int32)

In [106]:
np.flip(b,axis=1)

array([[15, 33, 35, 12],
       [66, 35, 53, 48],
       [95, 63, 72, 99],
       [10, 43, 92, 85],
       [74,  3, 86, 18],
       [10, 66, 71, 69]], dtype=int32)

## 16. np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [107]:
a

array([99, 32, 75, 68, 76, 31, 49, 78, 18, 97,  6, 59, 32, 68, 35],
      dtype=int32)

In [110]:
np.put(a,[0,1],[110,550]) # did the permanent changes

# Indexes can be contineuous or non-contineuous

In [111]:
print(a)

[110 550  75  68  76  31  49  78  18  97   6  59  32  68  35]


## 17. np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [112]:
a

array([110, 550,  75,  68,  76,  31,  49,  78,  18,  97,   6,  59,  32,
        68,  35], dtype=int32)

In [117]:
np.delete(a,[0])    # need to pass indexes

array([550,  75,  68,  76,  31,  49,  78,  18,  97,   6,  59,  32,  68,
        35], dtype=int32)

In [118]:
np.delete(a,[2,4,7])    

array([110, 550,  68,  31,  49,  18,  97,   6,  59,  32,  68,  35],
      dtype=int32)

## 18. Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [135]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)          # all without repetation

array([1, 2, 3, 4, 5, 6, 7])

In [136]:
np.intersect1d(m,n)   # common

array([3, 4, 5])

In [137]:
np.setdiff1d(m,n)    # in m, not in n

array([1, 2])

In [138]:
np.setdiff1d(n,m)    # in n, not in m

array([6, 7])

In [139]:
np.setxor1d(m,n)     # remove common and keep remaning

array([1, 2, 6, 7])

In [140]:
# np.in1d(m,1)

# ---> DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead

## 19. np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [131]:
a

array([110, 550,  75,  68,  76,  31,  49,  78,  18,  97,   6,  59,  32,
        68,  35], dtype=int32)

In [133]:
np.clip(a,a_min=20, a_max=70)

array([70, 70, 70, 68, 70, 31, 49, 70, 20, 70, 20, 59, 32, 68, 35],
      dtype=int32)